<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "renolit-ajax"
 * Auto generated by Extension Builder 2022-03-09
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'RENOLIT Ajax',
    'description' => 'RENOLIT Ajax - Sample',
    'category' => 'plugin',
    'author' => 'Timo Feuerstein',
    'author_email' => 'timo.feuerstein@renolit.com',
    'state' => 'stable',
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
